version: '3'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: apiUser
      POSTGRES_USER: userApi
      POSTGRES_PASSWORD: randompassword
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgresql_data: